### ISSUE TITLE
请问如何实现两个插件之间的信号槽绑定？

### ISSUE THREAD

**Issue by Joyed-ZHTX** [xueyu200/CbersUI#1]
# 请问如何实现两个插件之间的信号槽的操作？
很老的项目了，不知道您是否还关注这个项目。
我想在一个command插件里边，通过点击操作来控制一个view插件，但是没有找到获取到view插件的实例的办法。
我参考了x3py的文档也只找到`x3::Object<T>(clsidT)`来实例化对象，但是这个对象并不是之前已经实例化展示在界面上的view。而x3py的event机制也只能绑定到类的静态成员函数。
**所以想请教您一下，有什么办法能够获取到两个已经实例化的对象的指针，然后绑定Qt的信号槽？**

**Comment by longhuan2018** [comment]
你可以查看一下IUICore，通过它可以查询出来所有已加载的插件

**Comment by Joyed-ZHTX** [comment]
谢谢，问题已解决^_^
